// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Déterminer l'URL Supabase à utiliser
// Si le mock server local est disponible, l'utiliser
// Sinon, utiliser Supabase Cloud
const getSupabaseUrl = () => {
  // Safe access to import.meta.env for Node.js environments
  const env = (import.meta as any).env;
  const envUrl = env?.VITE_SUPABASE_URL;
  
  if (envUrl) return envUrl;
  
  // Essayer le mock local d'abord
  if (typeof window !== 'undefined' && window.location.hostname === 'localhost') {
    return 'http://localhost:3001';
  }
  
  // En environnement de développement (ou script Node), utiliser le mock local par défaut
  // si aucune URL n'est définie
  if (typeof window === 'undefined') {
    return 'http://localhost:3001';
  }

  // Si on est dans le navigateur mais pas sur localhost (ex: Codespace),
  // on utilise l'URL relative pour passer par le proxy Vite
  return window.location.origin;
  
  // Fallback à Supabase Cloud
  // return "https://jstgllotjifmgjxjsbpm.supabase.co";
};

const SUPABASE_URL = getSupabaseUrl();
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpzdGdsbG90amlmbWdqeGpzYnBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NzA0NDIsImV4cCI6MjA3MzQ0NjQ0Mn0.g-Zllg8NqrqNg-do5v2TCakK4RXUb6KAyvhS_yEiks4";

console.log('🔌 Supabase URL:', SUPABASE_URL);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const storageAdapter = typeof localStorage !== 'undefined' ? localStorage : {
  getItem: (key: string) => null,
  setItem: (key: string, value: string) => {},
  removeItem: (key: string) => {},
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: storageAdapter,
    persistSession: true,
    autoRefreshToken: true,
  }
});