// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Déterminer l'URL Supabase à utiliser
// Si le mock server local est disponible, l'utiliser
// Sinon, utiliser Supabase Cloud
const getSupabaseUrl = () => {
  // Safe access to import.meta.env for Node.js environments
  const env = (import.meta as any).env;
  const envUrl = env?.VITE_SUPABASE_URL;
  
  // En local, on privilégie le proxy Vite (qui pointe vers le mock server ou le cloud selon config)
  // Cela évite les problèmes de CORS et de DNS si internet est coupé
  if (typeof window !== 'undefined' && window.location.hostname === 'localhost') {
    console.log('🔧 Mode Localhost détecté : Utilisation du proxy Vite pour Supabase');
    return window.location.origin;
  }
  
  if (envUrl) return envUrl;
  
  // Fallback to the real Supabase URL if env var is missing
  return "https://jstgllotjifmgjxjsbpm.supabase.co";
};

const SUPABASE_URL = getSupabaseUrl();
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpzdGdsbG90amlmbWdqeGpzYnBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NzA0NDIsImV4cCI6MjA3MzQ0NjQ0Mn0.g-Zllg8NqrqNg-do5v2TCakK4RXUb6KAyvhS_yEiks4";

console.log('🔌 Supabase URL:', SUPABASE_URL);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const storageAdapter = typeof localStorage !== 'undefined' ? localStorage : {
  getItem: (key: string) => null,
  setItem: (key: string, value: string) => {},
  removeItem: (key: string) => {},
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: storageAdapter,
    persistSession: true,
    autoRefreshToken: true,
  }
});