name: Deploy Vite App to GitHub Pages

on:
  push:
    branches:
      - main  # déploie quand tu pousses sur la branche main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages   # Branche de déploiement
          folder: dist       # Dossier de build (dist par défaut avec Vite)
