name: Deploy Vite React App to GitHub Pages

on:
  push:
    branches:
      - main  # Déploiement à chaque push sur main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Installer les dépendances
      - name: Install dependencies
        run: npm ci

      # 4. Build du projet Vite
      - name: Build project
        run: npm run build

      # 5. Déployer sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.apimagique }}  # Ton PAT
          publish_dir: ./dist                           # Dossier de build
          user_name: "Nikkoola22"
          user_email: "nikkoola22@example.com"
          keep_files: true                              # Garde les fichiers précédents
